global:
  scrape_interval: 15s

rule_files:
  - rules/*.yml

scrape_configs:
  - job_name: clearcost-api
    metrics_path: /metrics
    scheme: https
    static_configs:
      - targets:
          - api:3000

    authorization:
      type: Bearer
      credentials: ck_...your_api_key...
