global:
  scrape_interval: 15s

rule_files:
  - rules/*.yml

scrape_configs:
  - job_name: clearcost-api
    metrics_path: /metrics
    static_configs:
      - targets:
          - api:3000 # replace with your API host:port or k8s service
