apiVersion: 1
groups:
  - name: Clearcost API HTTP
    folder: Clearcost
    interval: 1m
    rules:
      - uid: api-5xx-spike
        title: HTTP 5xx > 1 rps (5m)
        condition: A
        data:
          - refId: A
            datasourceUid: prometheus
            queryType: timeSeriesQuery
            relativeTimeRange: { from: 300, to: 0 }
            model:
              expr: "sum(rate(http_server_requests_total{status_code=~\"5..\"}[5m])) > 1"
              instant: true
        annotations:
          summary: "API 5xx spike"
        labels: { severity: critical }

      - uid: api-latency-p95
        title: p95 Latency > 1s (5m)
        condition: A
        data:
          - refId: A
            datasourceUid: prometheus
            queryType: timeSeriesQuery
            relativeTimeRange: { from: 300, to: 0 }
            model:
              expr: "histogram_quantile(0.95, sum by (le) (rate(http_server_request_duration_seconds_bucket[5m]))) > 1"
              instant: true
        annotations:
          summary: "High API latency"
        labels: { severity: warning }
