// Keep in sync with keys registered in lib/cron/registry.ts.
export const COMMAND_KEYS = [
  'fx:refresh',
  'import:de-minimis:official',
  'import:de-minimis:openai',
  'import:de-minimis:seed-baseline',
  'import:de-minimis:trade-gov',
  'import:de-minimis:zonos',
  'import:duties',
  'import:duties:cn-mfn-pdf',
  'import:duties:eu-backfill',
  'import:duties:eu-daily',
  'import:duties:jp-all',
  'import:duties:jp-fta',
  'import:duties:jp-mfn',
  'import:duties:llm-crosscheck',
  'import:duties:llm-grok',
  'import:duties:llm-openai',
  'import:duties:us-all',
  'import:duties:us-fta',
  'import:duties:us-mfn',
  'import:duties:wits',
  'crawl:notices',
  'crawl:notices:fetch-docs',
  'crawl:notices:json',
  'import:freight',
  'import:hs6',
  'import:hs:ahtn',
  'import:hs:eu-hs6',
  'import:hs:eu-taric',
  'import:hs:uk10',
  'import:hs:us-hts10',
  'import:programs:load-members',
  'import:programs:seed',
  'import:prune',
  'import:surcharges',
  'import:surcharges:llm-crosscheck',
  'import:surcharges:llm-grok',
  'import:surcharges:llm-openai',
  'import:surcharges:us-all',
  'import:surcharges:us-aphis',
  'import:surcharges:us-fda',
  'import:surcharges:us-trade-remedies',
  'import:sweep-stale',
  'import:vat',
  'import:vat:llm-openai',
  'import:vat:llm-grok',
  'import:vat:llm-crosscheck',
  'seed:countries:basic',
  'seed:trade-programs:us',
  'report:coverage',
] as const;

export type CommandKey = (typeof COMMAND_KEYS)[number];
