version: '3.8'
services:
  prometheus:
    image: prom/prometheus:v2.54.1
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports: ['9090:9090']

  grafana:
    image: grafana/grafana:10.4.3
    environment:
      - GF_SERVER_ROOT_URL=http://localhost:3001
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/provisioning/alerting:/etc/grafana/provisioning/alerting
    ports: ['3001:3000']
    depends_on: [prometheus]
