name: Cron Imports (Nightly)

on:
  schedule:
    - cron: '7 3 * * *' # daily 03:07 UTC
  workflow_dispatch: { }

concurrency:
  group: cron-nightly
  cancel-in-progress: false

jobs:
  nightly:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      API: ${{ secrets.CLEARCOST_API_URL }}
      API_KEY: ${{ secrets.CLEARCOST_TASKS_API_KEY }} # key with granular "tasks:*" scopes
      RUN_URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
    steps:
      - name: FX daily (ECB)
        run: |
          curl --fail-with-body --show-error --silent \
            --retry 3 --retry-all-errors -X POST \
            -H "x-api-key: $API_KEY" \
            "${API%/}/internal/cron/fx/daily"

      - name: VAT (OECD/IMF auto)
        run: |
          curl --fail-with-body --show-error --silent \
            --retry 3 --retry-all-errors -X POST \
            -H "x-api-key: $API_KEY" \
            "${API%/}/internal/cron/import/vat/auto"

      # Duties: native/authoritative
      - name: UK MFN
        run: |
          curl --fail-with-body --show-error --silent \
            --retry 3 --retry-all-errors -X POST \
            -H "x-api-key: $API_KEY" \
            "${API%/}/internal/cron/import/duties/uk-mfn"

      - name: UK Preferential
        run: |
          curl --fail-with-body --show-error --silent \
            --retry 3 --retry-all-errors -X POST \
            -H "x-api-key: $API_KEY" \
            "${API%/}/internal/cron/import/duties/uk-fta"

      - name: EU MFN (TARIC)
        run: |
          curl --fail-with-body --show-error --silent \
            --retry 3 --retry-all-errors -X POST \
            -H "x-api-key: $API_KEY" \
            "${API%/}/internal/cron/import/duties/eu-mfn"

      - name: EU Preferential (TARIC)
        run: |
          curl --fail-with-body --show-error --silent \
            --retry 3 --retry-all-errors -X POST \
            -H "x-api-key: $API_KEY" \
            "${API%/}/internal/cron/import/duties/eu-fta"

      - name: US MFN (HTS General)
        run: |
          curl --fail-with-body --show-error --silent \
            --retry 3 --retry-all-errors -X POST \
            -H "x-api-key: $API_KEY" \
            "${API%/}/internal/cron/import/duties/us-mfn"

      - name: US Preferential (HTS Special)
        run: |
          curl --fail-with-body --show-error --silent \
            --retry 3 --retry-all-errors -X POST \
            -H "x-api-key: $API_KEY" \
            "${API%/}/internal/cron/import/duties/us-preferential"

      # Surcharges
      - name: US Trade Remedies (301/232) from HTS
        run: |
          curl --fail-with-body --show-error --silent \
            --retry 3 --retry-all-errors -X POST \
            -H "x-api-key: $API_KEY" \
            -H "content-type: application/json" \
            -d '{}' \
            "${API%/}/internal/cron/import/surcharges/us-trade-remedies"

      - name: US Surcharges (All)
        run: |
          curl --fail-with-body --show-error --silent \
            --retry 3 --retry-all-errors -X POST \
            -H "x-api-key: $API_KEY" \
            -H "content-type: application/json" \
            -d '{"batchSize":5000}' \
            "${API%/}/internal/cron/import/surcharges/us-all"

      # JSON-driven (optional)
      - name: Import Surcharges (JSON)
        run: |
          curl --fail-with-body --show-error --silent \
            --retry 3 --retry-all-errors -X POST \
            -H "x-api-key: $API_KEY" \
            "${API%/}/internal/cron/import/surcharges"

      - name: Import Freight Cards
        run: |
          curl --fail-with-body --show-error --silent \
            --retry 3 --retry-all-errors -X POST \
            -H "x-api-key: $API_KEY" \
            "${API%/}/internal/cron/import/freight"

      # Notifications — guarded so missing webhooks don't fail the job
      - name: Slack (success)
        if: success()
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          if [ -n "${SLACK_WEBHOOK_URL:-}" ]; then
            curl -fsS -X POST -H 'Content-type: application/json' \
              --data "{\"text\":\"✅ ${{ github.workflow }} succeeded in ${{ github.repository }} on \\\`${{ github.ref_name }}\\\`\\n${RUN_URL}\"}" \
              "$SLACK_WEBHOOK_URL"
          fi

      - name: Slack (failure)
        if: failure()
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          if [ -n "${SLACK_WEBHOOK_URL:-}" ]; then
            curl -fsS -X POST -H 'Content-type: application/json' \
              --data "{\"text\":\"🚨 ${{ github.workflow }} failed in ${{ github.repository }} on \\\`${{ github.ref_name }}\\\`\\n${RUN_URL}\"}" \
              "$SLACK_WEBHOOK_URL"
          fi

      - name: Discord (success)
        if: success()
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          if [ -n "${DISCORD_WEBHOOK_URL:-}" ]; then
            content="✅ **${{ github.workflow }}** succeeded in **${{ github.repository }}** on \`${{ github.ref_name }}\`\n${RUN_URL}"
            curl -fsS -H "Content-Type: application/json" -X POST \
              -d "{\"content\":\"$content\"}" \
              "$DISCORD_WEBHOOK_URL"
          fi

      - name: Discord (failure)
        if: failure()
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          if [ -n "${DISCORD_WEBHOOK_URL:-}" ]; then
            content="🚨 **${{ github.workflow }}** failed in **${{ github.repository }}** on \`${{ github.ref_name }}\`\n${RUN_URL}"
            curl -fsS -H "Content-Type: application/json" -X POST \
              -d "{\"content\":\"$content\"}" \
              "$DISCORD_WEBHOOK_URL"
          fi
