name: Sweep stale imports (hourly)

on:
  schedule:
    - cron: '0 * * * *' # hourly at :00
  workflow_dispatch: { }

concurrency:
  group: imports-sweep-stale
  cancel-in-progress: false

jobs:
  sweep:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Sweep stale imports via API
        env:
          API: ${{ secrets.CLEARCOST_API_URL }}
          API_KEY: ${{ secrets.CLEARCOST_TASKS_API_KEY }} # scope: tasks:ops:sweep-stale
          THRESHOLD_MINUTES: ${{ vars.IMPORTS_SWEEP_THRESHOLD_MINUTES }}
        run: |
          set -euo pipefail
          : "${API:?missing CLEARCOST_API_URL secret}"
          : "${API_KEY:?missing CLEARCOST_TASKS_API_KEY secret}"
          THRESHOLD="${THRESHOLD_MINUTES:-30}"

          RESP="$(curl --fail-with-body --show-error --silent \
            --retry 5 --retry-all-errors --max-time 60 \
            -X POST \
            -H "x-api-key: ${API_KEY}" \
            -H "content-type: application/json" \
            -d "{\"thresholdMinutes\": ${THRESHOLD}}" \
            "${API%/}/internal/cron/imports/sweep-stale")"

          echo "$RESP" | jq .
          jq -e '.ok == true' >/dev/null <<<"$RESP"
