name: Sweep stale imports (hourly)

on:
  schedule:
    - cron: '0 * * * *'   # hourly at :00
  workflow_dispatch: { }

concurrency:
  group: imports-sweep-stale
  cancel-in-progress: false

jobs:
  sweep:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Sweep stale imports via API
        env:
          API_BASE: ${{ secrets.API_BASE }}
          ADMIN_TOKEN: ${{ secrets.ADMIN_TOKEN }}
          THRESHOLD_MINUTES: ${{ vars.IMPORTS_SWEEP_THRESHOLD_MINUTES }}
        run: |
          set -euo pipefail
          : "${API_BASE:?missing API_BASE secret}"
          : "${ADMIN_TOKEN:?missing ADMIN_TOKEN secret}"
          THRESHOLD="${THRESHOLD_MINUTES:-30}"

          RESP="$(curl --fail-with-body --show-error --silent \
            --retry 5 --retry-all-errors --max-time 60 \
            -X POST \
            -H "x-admin-token: ${ADMIN_TOKEN}" \
            -H "content-type: application/json" \
            -d "{\"thresholdMinutes\": ${THRESHOLD}}" \
            "${API_BASE%/}/internal/cron/imports/sweep-stale")"

          # Pretty-print & basic guard
          echo "$RESP" | jq .
          OK="$(echo "$RESP" | jq -r '.ok')"
          if [ "$OK" != "true" ]; then
            echo "Sweeper returned non-ok response"
            exit 1
          fi
